import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        {/* Spline 3D Background */}
        <div className="fixed inset-0 -z-10 w-full h-full overflow-hidden pointer-events-none">
          <iframe 
            src="https://my.spline.design/particles-ALVTe7DBbXbMfJCLJv0lda5a/" 
            className="w-full h-full border-none"
            title="Spline Background"
          ></iframe>
        </div>
        
        {/* Main App Content */}
        <div className="relative z-0 flex-1 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
