"""
RFP Schemas — Request and response models for RFP processing.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional


class RFPParseRequest(BaseModel):
    jobId: str = Field(..., description="Unique job ID generated by the backend")
    blobUrl: str = Field(..., description="Azure Blob Storage SAS URL for the uploaded PDF")
    filename: str = Field(..., description="Original name of the uploaded document")


class ParserResult(BaseModel):
    parent_sections_count: int
    raw_markdown_preview: str
    metadata: Dict[str, Any]
